# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98f859296acf85081d99fa220628514f38fd9f21bc2990c837e63552c2bd77a22dbb8e674e2ed0590a218eb05f2b62764696029279d31465930629bf7a9d57db

test:
  secret_key_base: 1ced40fbf30647f353c240728c529e13de57e96f10e3a61fbfc561f7bbcb9a4a76e90078084785beb7074f9cb483b3d7397b0a055c07ce4bb7a3e2d91b069975

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
